using ECFR.Core.Models;
using ECFR.Data.EFModels;
using ECFR.Repositories.Mapper;

namespace ECFR.Repositories
{
    public class ECFRDataStoreRepository
    {

        /// <summary>
        /// Insert Agency data into the database using Entity Framework or Dapper. 
        /// This method will take a json string as input, deserialize it to a list of AgencyModel objects, 
        /// map those objects to AgencyRaw objects using the AgencyMapper, and then insert those objects into the database. 
        /// It will also map the cfr_references to CfrReferenceRaw objects and insert them into the database as well.
        /// </summary>
        /// <param name="agencies">List<AgencyModel></param>
        /// <exception cref="ApplicationException"></exception>
        public void InsertAgencyData(List<AgencyModel> agencies)
        {
            try
            {
                if (agencies != null)
                {
                    //Map agencyModel to AgencyRaw using the AgencyMapper
                    var agencyMapper = new AgencyMapper();
                    var agencyRawList = agencies.Select(a => agencyMapper.Map(a)).ToList();

                    //insert agencyRawList into a database using Entity Framework or Dapper
                    using (var context = new EcfrdbMdfContext())
                    {
                        context.Agencies.AddRange(agencyRawList);
                        context.SaveChanges();

                        //update agencyModel with the Ids generated by the database for the inserted AgencyRaw
                        //objects so that we can use those Ids to insert the related cfr_references into the database
                        foreach (var agency in agencies)
                        {
                            var matchingAgencyRaw = agencyRawList.FirstOrDefault(a => a.Name == agency.Name && a.Name == agency.Name);
                            if (matchingAgencyRaw != null)
                            {
                                agency.Id = matchingAgencyRaw.Id;
                            }
                        }
                    }

                    //Map agency cfr_references to CfrReferenceRaw  using the CfrReferenceMapper
                    //and AgencyCfrReferenceRelRaw manually since there is no direct mapping for the relationship
                    //between Agency and CfrReference in the data model
                        var cfrReferenceRawList = new List<CfrReference>();
                        var agencyCfrReferenceRelRawList = new List<AgencyCfrReferenceRel>();
                    var cfrReferenceMapper = new CfrReferenceMapper();
                    foreach (var agency in agencies)
                    {
                        if (agency.Cfr_references != null)
                        {
                            cfrReferenceRawList.AddRange(agency.Cfr_references.Select(c => cfrReferenceMapper.Map(c)).ToList());
                        }
                    }
                    using (var context = new EcfrdbMdfContext())
                    {
                        var distinctRefList = cfrReferenceRawList.Distinct();
                        context.CfrReferences.AddRange(distinctRefList);
                        context.SaveChanges();
                    }

                    foreach (var agency in agencies)
                    {
                        foreach (var cfr in agency.Cfr_references)
                        {
                            var matchingCfrReferenceRaw = cfrReferenceRawList.FirstOrDefault(c => c.Title == cfr.Title
                                                                                            && c.SubTitle == cfr.SubTitle
                                                                                            && c.Chapter == cfr.Chapter
                                                                                            && c.SubChapter == cfr.SubChapter);
                            if (matchingCfrReferenceRaw != null)
                            {
                                cfr.Id = matchingCfrReferenceRaw.Id;
                            }
                        }
                        // Here you can add code to insert the cfrReferenceRawList into a database
                        agencyCfrReferenceRelRawList.AddRange(agency.Cfr_references.Select(c => new AgencyCfrReferenceRel
                        {
                            AgencyId = agency.Id,
                            TitleId = c.Id,
                        }
                        ).ToList());
                    }

                    using (var context = new EcfrdbMdfContext())
                    {
                        context.AgencyCfrReferenceRels.AddRange(agencyCfrReferenceRelRawList.Distinct());
                        context.SaveChanges();
                    }
                }
            }
            catch (Exception ex)
            {
                throw new ApplicationException("Error while inserting agency data: " + ex.Message);
            }
        }

        /// <summary>
        /// Insert AgencySnapshot data into the database using Entity Framework or Dapper.
        /// </summary>
        /// <param name="snapshotModel">AgencySnapshotModel</param>
        /// <exception cref="ApplicationException"></exception>
        public void InsertAgencySnapshotData(AgencySnapshotModel snapshotModel)
        {
            try
            {
                if (snapshotModel != null)
                {
                    //Map AgencySnapshotModel to AgencySnapshot using the AgencySnapshotMapper
                    var agencySnapshotMapper = new AgencySnapshotMapper();
                    var snapshotRaw = agencySnapshotMapper.Map(snapshotModel);
                    //insert snapshotRaw into a database using Entity Framework or Dapper
                    using (var context = new EcfrdbMdfContext())
                    {
                        context.AgencySnapshots.Add(snapshotRaw);
                        context.SaveChanges();
                        context.Dispose();
                    }
                }
            }
            catch (Exception ex)
            {
                throw new ApplicationException("Error while inserting agency snapshot data: " + ex.Message);
            }
        }

    }
}
